const SUPABASE_URL='https://tpvhxauivmjgfcugpldp.supabase.co';
const SUPABASE_KEY='sb_publishable_0n__ZztsS8BQtdVn5lhmmA_WWuHjVg7';
const LOGIN_PASSWORD='1234';
const CUSTOMER_STORAGE_KEY='tabbaraCustomers',PENDING_ORDERS_KEY='tabbara_pending_orders',MENU_STORAGE_KEY='tabbaraMenu',DEVICE_ID_KEY='tabbaraDeviceId',DELIVERY_CHARGE_KEY='tabbaraDeliveryCharge';
const GLOBAL_GRILL_KEY='tabbaraGrillSurcharge',GLOBAL_FRY_KEY='tabbaraFrySurcharge';
const DEFAULT_DELIVERY_CHARGE=2,DEFAULT_GRILL_SURCHARGE=3,DEFAULT_FRY_SURCHARGE=3;
const CATEGORIES=['🐟 الأسماك','🦐 ثمار البحر','🍽️ الوجبات والساندويش','🎁 العروض','🥗 المقبلات','🥬 السلطات','🥤 المشروبات'];
const DEFAULT_MENU=[
{id:'fish_ajaj',name:'أجاج',category:'🐟 الأسماك',type:'weight',pricing:{base:12},available:true},
{id:'fish_boraq',name:'براق',category:'🐟 الأسماك',type:'weight',pricing:{base:14},available:true},
{id:'fish_sardine',name:'سردين',category:'🐟 الأسماك',type:'weight',pricing:{base:8},available:true},
{id:'fish_laqz_sandy',name:'لقز رملي',category:'🐟 الأسماك',type:'weight',pricing:{base:16},available:true},
{id:'fish_laqz_rocky',name:'لقز صخري',category:'🐟 الأسماك',type:'weight',pricing:{base:18},available:true},
{id:'fish_sultan',name:'سلطان',category:'🐟 الأسماك',type:'weight',pricing:{base:15},available:true},
{id:'fish_masqar',name:'مسقار',category:'🐟 الأسماك',type:'weight',pricing:{base:13},available:true},
{id:'fish_malifa',name:'مليفة',category:'🐟 الأسماك',type:'weight',pricing:{base:12},available:true},
{id:'fish_jarbidi',name:'جربيدي',category:'🐟 الأسماك',type:'weight',pricing:{base:14},available:true},
{id:'fish_armout_blond',name:'عرموط أشقر',category:'🐟 الأسماك',type:'weight',pricing:{base:11},available:true},
{id:'fish_armout_cut',name:'عرموط مقطع',category:'🐟 الأسماك',type:'weight',pricing:{base:12},available:true},
{id:'seafood_shrimp_medium',name:'قريدس وسط',category:'🦐 ثمار البحر',type:'weight',pricing:{base:16},available:true},
{id:'seafood_shrimp_large',name:'قريدس كبير',category:'🦐 ثمار البحر',type:'weight',pricing:{base:20},available:true},
{id:'seafood_calamari',name:'كالامار',category:'🦐 ثمار البحر',type:'weight',pricing:{base:14},available:true},
{id:'seafood_fillet_fresh',name:'فيليه طازج',category:'🦐 ثمار البحر',type:'weight',pricing:{base:17},available:true},
{id:'seafood_fillet_crispy',name:'فيليه مقرمش',category:'🦐 ثمار البحر',type:'weight',pricing:{base:18},available:true},
{id:'seafood_mix',name:'ثمار البحر',category:'🦐 ثمار البحر',type:'sizes',sizes:{صغير:15,وسط:22,سطل:35},available:true},
{id:'meal_free_fish',name:'سمكة حرة',category:'🍽️ الوجبات والساندويش',type:'meal',prices:{وجبة:15,ساندويش:8},available:true},
{id:'meal_shrimp',name:'قريدس',category:'🍽️ الوجبات والساندويش',type:'meal',prices:{وجبة:15,ساندويش:8},available:true},
{id:'meal_seafood',name:'ثمار البحر',category:'🍽️ الوجبات والساندويش',type:'meal',prices:{وجبة:16,ساندويش:9},available:true},
{id:'meal_calamari',name:'كالامار',category:'🍽️ الوجبات والساندويش',type:'meal',prices:{وجبة:14,ساندويش:8},available:true},
{id:'meal_sardine',name:'سردين',category:'🍽️ الوجبات والساندويش',type:'meal',prices:{وجبة:11,ساندويش:7},available:true},
{id:'app_sayadieh',name:'صيادية',category:'🥗 المقبلات',type:'sizes',sizes:{صغير:5,وسط:8,كبير:11},available:true},
{id:'app_mtabbal',name:'متبل',category:'🥗 المقبلات',type:'fixed',price:4,available:true},
{id:'app_shakshuka',name:'شكشوكة',category:'🥗 المقبلات',type:'fixed',price:5,available:true},
{id:'app_tarator',name:'طرطور كبير',category:'🥗 المقبلات',type:'fixed',price:4,available:true},
{id:'app_fries',name:'بطاطا مقلية',category:'🥗 المقبلات',type:'sizes',sizes:{صغير:3,وسط:5,كبير:7},available:true},
{id:'salad_tabouleh',name:'تبولة',category:'🥬 السلطات',type:'fixed',price:6,available:true},
{id:'salad_fattoush',name:'فتوش',category:'🥬 السلطات',type:'fixed',price:6,available:true},
{id:'salad_crab',name:'سلطة كراب',category:'🥬 السلطات',type:'fixed',price:8,available:true},
{id:'drink_pepsi',name:'Pepsi',category:'🥤 المشروبات',type:'sizes',sizes:{صغير:2,كبير:3},available:true},
{id:'drink_7up',name:'7up',category:'🥤 المشروبات',type:'sizes',sizes:{صغير:2,كبير:3},available:true},
{id:'drink_miranda',name:'Miranda',category:'🥤 المشروبات',type:'sizes',sizes:{صغير:2,كبير:3},available:true}
];
let deviceId=localStorage.getItem(DEVICE_ID_KEY);if(!deviceId){deviceId='device-'+Date.now()+'-'+Math.random().toString(36).slice(2,10);localStorage.setItem(DEVICE_ID_KEY,deviceId)}
let menu=[],cart=[],selectedOrderType='',currentCategory='',currentModalItem=null,deliveryCharge=DEFAULT_DELIVERY_CHARGE,grillSurcharge=DEFAULT_GRILL_SURCHARGE,frySurcharge=DEFAULT_FRY_SURCHARGE;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>Number(n||0).toFixed(2);
const normalizePhone=p=>{let s=String(p||'').replace(/\D/g,'');if(s.startsWith('00961'))s=s.slice(5);if(s.startsWith('961'))s=s.slice(3);if(s.startsWith('0'))s=s.slice(1);return s?'0'+s:''};
function loadSettings(){deliveryCharge=Number(localStorage.getItem(DELIVERY_CHARGE_KEY));if(!Number.isFinite(deliveryCharge))deliveryCharge=DEFAULT_DELIVERY_CHARGE;grillSurcharge=Number(localStorage.getItem(GLOBAL_GRILL_KEY));if(!Number.isFinite(grillSurcharge))grillSurcharge=DEFAULT_GRILL_SURCHARGE;frySurcharge=Number(localStorage.getItem(GLOBAL_FRY_KEY));if(!Number.isFinite(frySurcharge))frySurcharge=DEFAULT_FRY_SURCHARGE}
function loadMenu(){try{const x=JSON.parse(localStorage.getItem(MENU_STORAGE_KEY)||'null');if(Array.isArray(x)&&x.length){menu=x;return}}catch{}menu=JSON.parse(JSON.stringify(DEFAULT_MENU));localStorage.setItem(MENU_STORAGE_KEY,JSON.stringify(menu))}
function cloudRowToLocal(r){const d=r.data&&typeof r.data==='object'?r.data:{};const cat={'الأسماك':'🐟 الأسماك','ثمار البحر':'🦐 ثمار البحر','الوجبات والساندويش':'🍽️ الوجبات والساندويش','العروض':'🎁 العروض','المقبلات':'🥗 المقبلات','السلطات':'🥬 السلطات','المشروبات':'🥤 المشروبات'};const def=DEFAULT_MENU.find(x=>String(x.id)===String(r.id));const item={id:String(r.id),name:r.name||'',category:cat[r.category]||r.category||'',type:r.type||def?.type||'fixed',available:r.available!==false};if(item.type==='weight'){item.pricing={base:Number(d.base??d.basePrice??def?.pricing?.base??0)}}else if(item.type==='sizes'){item.sizes={...(d.sizes||def?.sizes||{})}}else if(item.type==='meal')item.prices={وجبة:Number(d.meal??d.وجبة??d.prices?.وجبة??0),ساندويش:Number(d.sandwich??d.ساندويش??d.prices?.ساندويش??0)};else if(item.type==='offer'){item.price=Number(d.price??r.price??0);item.details=d.details||'';item.items=Array.isArray(d.items)?d.items:[]}else item.price=Number(d.price??r.price??def?.price??0);return item}
function localToCloudRow(i){let data={};if(i.type==='weight'){data.base=Number(i.pricing?.base||0)}else if(i.type==='sizes'){data.sizes={...(i.sizes||{})}}else if(i.type==='meal'){data.meal=Number(i.prices?.وجبة||0);data.sandwich=Number(i.prices?.ساندويش||0)}else if(i.type==='offer'){data.price=Number(i.price||0);data.details=i.details||'';data.items=Array.isArray(i.items)?i.items:[]}else data.price=Number(i.price||0);return{id:String(i.id),name:i.name||'',category:i.category||'',type:i.type||'fixed',available:i.available!==false,data,updated_at:new Date().toISOString()}}
async function syncMenuFromCloud(){if(!navigator.onLine)return;try{const r=await api('/rest/v1/pos_menu?select=*&limit=1000');if(r.ok){const rows=await r.json();if(rows.length){menu=rows.map(cloudRowToLocal);saveMenuLocal();renderCategories();renderItems()}}}catch(e){console.warn(e)}}
async function syncMenuToCloud(){if(!navigator.onLine)return;try{for(const i of menu)await api('/rest/v1/pos_menu',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(localToCloudRow(i))})}catch(e){console.warn(e)}}
function saveMenuLocal(){localStorage.setItem(MENU_STORAGE_KEY,JSON.stringify(menu))}
async function api(path,opt={}){const headers=Object.assign({apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':'application/json'},opt.headers||{});return fetch(SUPABASE_URL+path,{...opt,headers})}
function setStatus(){const e=document.getElementById('connectionStatus');e.textContent=navigator.onLine?'🟢 متصل':'🔴 أوفلاين';e.className='status-badge '+(navigator.onLine?'status-online':'status-offline')}
function login(){if(document.getElementById('loginPassword').value===LOGIN_PASSWORD){sessionStorage.setItem('tabbaraLoggedIn','1');document.getElementById('loginScreen').style.display='none'}else document.getElementById('loginError').style.display='block'}
function logout(){sessionStorage.removeItem('tabbaraLoggedIn');location.reload()}
function setOrderType(t){selectedOrderType=t;document.getElementById('orderType').textContent=t;document.getElementById('deliveryBtn').classList.toggle('active',t==='Delivery');document.getElementById('pickupBtn').classList.toggle('active',t==='استلام من المحل');renderCart()}
function renderCategories(){const box=document.getElementById('categories');box.innerHTML=CATEGORIES.map(c=>`<button class="${c===currentCategory?'active':''}" onclick="selectCategory('${esc(c).replace(/'/g,"\\'")}')">${c}</button>`).join('');if(!currentCategory)selectCategory(CATEGORIES[0])}
function selectCategory(c){currentCategory=c;renderCategories();renderItems()}
function effectivePrice(item,prep){if(item.type==='weight')return Number(item.pricing?.base||0)+((prep==='grill')?grillSurcharge:(prep==='fry'?frySurcharge:0));if(item.type==='fixed')return Number(item.price||0);return 0}
function stockAvailable(i){return i.available!==false}
function displayPrice(i){if(i.type==='weight')return `من $${money(i.pricing?.base)} / كغ`;if(i.type==='sizes')return `من $${money(Math.min(...Object.values(i.sizes||{0:0}).map(Number)))}`;if(i.type==='meal')return `$${money(i.prices?.وجبة)}`;return `$${money(i.price)}`}
function renderItems(){const box=document.getElementById('items');if(!box)return;const arr=menu.filter(i=>i.category===currentCategory);box.innerHTML=arr.map(i=>{const sold=i.available===false;return `<div class="menu-item ${sold?'disabled':''}" onclick="openItem('${esc(i.id).replace(/'/g,"\\'")}')"><div class="menu-item-name">${esc(i.name)}</div><div class="menu-item-price">${sold?'❌ منتهي':displayPrice(i)}</div>${sold?'<span class="badge">منتهي</span>':''}</div>`}).join('')}
function openItem(id){const i=menu.find(x=>x.id===id);if(!i||i.available===false||!stockAvailable(i))return alert('هذا الصنف منتهي حالياً.');currentModalItem=i;let body='';
if(i.type==='offer')body=`<div class="offer-details"><h4>🎁 تفاصيل العرض</h4><p>${esc(i.details||'لا توجد تفاصيل إضافية.')}</p>${(i.items||[]).length?`<ul>${i.items.map(x=>`<li>${esc(x.name)}${x.quantity&&Number(x.quantity)>1?' × '+x.quantity:''}</li>`).join('')}</ul>`:''}</div><div class="option-group"><label>الكمية</label><input id="itemQty" class="modal-input" type="number" min="1" step="1" value="1"></div><div class="total">السعر: $${money(i.price)}</div>`;
else if(i.type==='weight')body=`<div class="option-group"><label>طريقة التحضير</label><div class="option-buttons"><button id="prep-raw" class="option-btn active" onclick="choosePrep('raw')">ني</button><button id="prep-fry" class="option-btn" onclick="choosePrep('fry')">قلي +$${money(frySurcharge)}</button><button id="prep-grill" class="option-btn" onclick="choosePrep('grill')">شوي +$${money(grillSurcharge)}</button></div></div><div class="option-group"><label>الكمية بالكيلو</label><input id="weightQty" class="modal-input" type="number" min="0.1" step="0.1" value="1"></div><div id="modalPrice" class="total">السعر: $${money(effectivePrice(i,'raw'))} / كغ</div>`;
else if(i.type==='sizes')body=`<div class="option-group"><label>الحجم</label><div class="size-options">${Object.entries(i.sizes||{}).map(([s,p],n)=>`<button class="size-option ${n===0?'active':''}" data-size="${esc(s)}" onclick="chooseSize(this)">${esc(s)}<br>$${money(p)}</button>`).join('')}</div></div><div class="option-group"><label>الكمية</label><input id="itemQty" class="modal-input" type="number" min="1" step="1" value="1"></div>`;
else if(i.type==='meal')body=`<div class="option-group"><label>الاختيار</label><div class="option-buttons"><button class="option-btn active" data-meal="وجبة" onclick="chooseMeal(this)">وجبة $${money(i.prices?.وجبة)}</button><button class="option-btn" data-meal="ساندويش" onclick="chooseMeal(this)">ساندويش $${money(i.prices?.ساندويش)}</button></div></div><div class="option-group"><label>الكمية</label><input id="itemQty" class="modal-input" type="number" min="1" step="1" value="1"></div>`;
else body=`<div class="option-group"><label>الكمية</label><input id="itemQty" class="modal-input" type="number" min="1" step="1" value="1"></div>`;
document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal-box"><div class="modal-header"><h3>${i.type==='offer'?'🎁':'🐟'} ${esc(i.name)}</h3><button onclick="closeModal()">✕</button></div><div class="modal-body">${body}<button class="modal-confirm-btn" onclick="addModalItem()">➕ إضافة إلى الطلب</button></div></div></div>`}
function addModalItem(){const i=currentModalItem;let qty,unitPrice,label,weight=0;if(i.type==='offer'){qty=Number(document.getElementById('itemQty').value);unitPrice=Number(i.price||0);label=i.name}else if(i.type==='weight'){qty=Number(document.getElementById('weightQty').value);if(!Number.isFinite(qty)||qty<=0)return alert('أدخل كمية صحيحة بالكيلو.');unitPrice=effectivePrice(i,modalPrep);weight=qty;label=`${i.name} - ${modalPrep==='fry'?'قلي':modalPrep==='grill'?'شوي':'ني'}`}else if(i.type==='sizes'){qty=Number(document.getElementById('itemQty').value);modalSize=modalSize||Object.keys(i.sizes||{})[0];unitPrice=Number(i.sizes[modalSize]);label=`${i.name} - ${modalSize}`}else if(i.type==='meal'){qty=Number(document.getElementById('itemQty').value);unitPrice=Number(i.prices?.[modalMeal]||0);label=`${i.name} - ${modalMeal}`}else{qty=Number(document.getElementById('itemQty').value);unitPrice=Number(i.price||0);label=i.name}if(!Number.isFinite(qty)||qty<=0)return alert('الكمية غير صحيحة.');cart.push({id:i.id,name:i.name,label,quantity:qty,weight,unitPrice,total:qty*unitPrice,preparation:i.type==='weight'?modalPrep:'',category:i.category});closeModal();renderCart()}
function renderCart(){const box=document.getElementById('cartItems');let total=cart.reduce((s,x)=>s+Number(x.total),0);if(selectedOrderType==='Delivery'&&cart.length)total+=deliveryCharge;if(!cart.length)box.innerHTML='<p>لا يوجد أصناف</p>';else box.innerHTML=cart.map((x,n)=>`<div class="cart-item"><div><strong>${esc(x.label)}</strong><br><small>${x.weight?money(x.weight)+' كغ × ':x.quantity+' × '}$${money(x.unitPrice)}</small></div><div class="quantity"><button onclick="removeCartItem(${n})">−</button><b>${x.weight?money(x.weight)+' كغ':x.quantity}</b><button onclick="increaseCartItem(${n})">+</button></div></div>`).join('');document.getElementById('total').textContent=money(total)}
function removeCartItem(n){cart.splice(n,1);renderCart()}function increaseCartItem(n){const x=cart[n],i=menu.find(m=>m.id===x.id);const add=x.weight||1;if(x.weight)x.weight=Number(x.weight)+0.1;else x.quantity=Number(x.quantity)+1;x.total=Number(x.quantity||x.weight)*Number(x.unitPrice);renderCart()}
function clearOrder(){cart=[];selectedOrderType='';document.getElementById('orderType').textContent='لم يتم الاختيار';document.getElementById('deliveryBtn').classList.remove('active');document.getElementById('pickupBtn').classList.remove('active');['name','phone','address','notes'].forEach(id=>document.getElementById(id).value='');renderCart()}
async function findCustomer(){const phone=normalizePhone(document.getElementById('phone').value);if(phone.length<8)return;try{const r=await api(`/rest/v1/customers?phone=eq.${encodeURIComponent(phone)}&select=*&limit=1`);if(r.ok){const a=await r.json();if(a[0]){document.getElementById('name').value=a[0].name||'';document.getElementById('address').value=a[0].address||'';document.getElementById('notes').value=a[0].notes||'';document.getElementById('customerMessage').textContent='✅ زبون موجود — تم تعبئة البيانات'}}}catch{}}
async function saveCustomer(){const phone=normalizePhone(document.getElementById('phone').value),name=document.getElementById('name').value.trim(),address=document.getElementById('address').value.trim(),notes=document.getElementById('notes').value.trim();if(!phone)return;if(!navigator.onLine){return}const r=await api('/rest/v1/customers?on_conflict=phone',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({phone,name,address,notes,updated_at:new Date().toISOString()})});if(!r.ok)console.warn('customer save',r.status,await r.text())}
function paymentMeta(){const p=document.getElementById('paymentMethod').value;return p==='cash'?'كاش':p==='card'?'بطاقة':'تحويل'}
function orderPayload(){const baseTotal=cart.reduce((s,x)=>s+Number(x.total),0),delivery=selectedOrderType==='Delivery'?deliveryCharge:0;const meta={__meta:true,payment_method:document.getElementById('paymentMethod').value,payment_label:paymentMeta(),delivery_charge:delivery,inventory_deducted:false};return{order_type:selectedOrderType,customer_name:document.getElementById('name').value.trim(),customer_phone:normalizePhone(document.getElementById('phone').value),customer_address:document.getElementById('address').value.trim(),notes:document.getElementById('notes').value.trim(),items:[...cart,meta],total:baseTotal+delivery,device_id:deviceId,sync_status:navigator.onLine?'synced':'pending',created_at:new Date().toISOString(),delivery_charge:delivery}}
async function deductInventory(){for(const x of cart){if(!x.weight)continue;const i=menu.find(m=>m.id===x.id);if(!i||i.stock==null)continue;i.stock=Math.max(0,Number(i.stock)-Number(x.weight));i.available=i.stock>0}saveMenuLocal();renderItems();await syncMenuToCloud()}
async function confirmOrder(){if(!selectedOrderType)return alert('اختار نوع الطلب أولاً.');if(!cart.length)return alert('أضف صنفاً واحداً على الأقل.');const payload=orderPayload();try{const r=await api('/rest/v1/orders',{method:'POST',body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());saveCustomer().catch(e=>console.warn('customer save',e));alert('✅ تم حفظ الطلب بنجاح');printOrder(payload);clearOrder()}catch(e){console.warn(e);payload.sync_status='pending';const q=JSON.parse(localStorage.getItem(PENDING_ORDERS_KEY)||'[]');q.push(payload);localStorage.setItem(PENDING_ORDERS_KEY,JSON.stringify(q));alert('📴 تم حفظ الطلب على الجهاز وسيتم مزامنته عند عودة الإنترنت.');printOrder(payload);clearOrder()}}
async function syncPendingOrders(){if(!navigator.onLine)return;const q=JSON.parse(localStorage.getItem(PENDING_ORDERS_KEY)||'[]');if(!q.length)return;const left=[];for(const o of q){try{const r=await api('/rest/v1/orders',{method:'POST',body:JSON.stringify(o)});if(!r.ok)throw 0}catch{left.push(o)}}localStorage.setItem(PENDING_ORDERS_KEY,JSON.stringify(left))}
function printOrder(o){const items=(o.items||[]).filter(x=>!x.__meta);const meta=(o.items||[]).find(x=>x.__meta)||{};const html=`<div style="width:80mm;font-family:Arial;direction:rtl;text-align:right;padding:8px;box-sizing:border-box"><h2 style="text-align:center;margin:0 0 6px">🐟 Tabbara Fish</h2><div style="text-align:center;font-size:12px">فاتورة طلب</div><div style="border-bottom:1px dashed #000;margin:8px 0"></div><div style="font-size:13px;line-height:1.7"><b>👤 اسم الزبون:</b> ${esc(o.customer_name||'غير محدد')}<br><b>📞 الهاتف:</b> ${esc(o.customer_phone||'غير محدد')}<br><b>📍 العنوان:</b> ${esc(o.customer_address||'غير محدد')}<br><b>📦 نوع الطلب:</b> ${esc(o.order_type||'')}</div><div style="border-bottom:1px dashed #000;margin:8px 0"></div>${items.map(x=>`<div style="margin:6px 0"><b>${esc(x.label||x.name||'')}</b><br>${x.weight?money(x.weight)+' كغ × ': '× '+(x.quantity||1)+' × '}$${money(x.unitPrice)} = $${money(x.total)}</div>`).join('')}<div style="border-top:1px dashed #000;padding-top:6px;margin-top:8px"><div><b>المجموع قبل التوصيل:</b> $${money(Number(o.total||0)-Number(o.delivery_charge||0))}</div><div><b>🛵 رسوم التوصيل:</b> $${money(o.delivery_charge||0)}</div><div style="font-size:17px;margin-top:5px"><b>المجموع النهائي: $${money(o.total)}</b></div><div style="margin-top:5px"><b>💳 طريقة الدفع:</b> ${esc(meta.payment_label||'كاش')}</div></div>${o.notes?`<div style="margin-top:8px"><b>ملاحظات:</b> ${esc(o.notes)}</div>`:''}</div>`;let p=document.getElementById('posPrintArea');if(!p){p=document.createElement('div');p.id='posPrintArea';document.body.appendChild(p)}p.innerHTML=html;document.body.classList.add('printing-invoice');setTimeout(()=>{window.print();document.body.classList.remove('printing-invoice')},100)}
function openModal(title,body){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal-box"><div class="modal-header"><h3>${title}</h3><button onclick="closeModal()">✕</button></div><div class="modal-body">${body}</div></div></div>`}
async function showOrders(){let rows=[];try{const r=await api('/rest/v1/orders?select=*&order=created_at.desc&limit=200');if(r.ok)rows=await r.json()}catch{}openModal('📋 الطلبات السابقة',`<div class="search-row"><input id="ordersSearch" placeholder="بحث باسم الزبون أو الهاتف" oninput="filterOrders()"></div><div id="ordersList">${rows.map(orderCard).join('')||'<p class="muted">لا توجد طلبات.</p>'}</div>`);window.__ordersRows=rows}
function orderCard(o){const d=new Date(o.created_at);const items=(Array.isArray(o.items)?o.items:[]).filter(x=>!x.__meta);const meta=(Array.isArray(o.items)?o.items:[]).find(x=>x.__meta)||{};return `<div class="receipt order-record" data-search="${esc((o.customer_name||'')+' '+(o.customer_phone||''))}"><b>${d.toLocaleString('ar-LB')}</b><br>👤 ${esc(o.customer_name||'زبون')} — ${esc(o.customer_phone||'')}<br>📦 ${esc(o.order_type||'')}<br>🧾 ${items.map(x=>esc(x.label||x.name)).join('، ')}<br><strong>💰 $${money(o.total)}</strong> — ${esc(meta.payment_label||'كاش')}<br><button class="primary" onclick="reprintExisting('${esc(o.id).replace(/'/g,"\\'")}')">🖨️ إعادة طباعة</button></div>`}
function filterOrders(){const q=document.getElementById('ordersSearch').value.toLowerCase();document.querySelectorAll('.order-record').forEach(e=>e.style.display=e.dataset.search.toLowerCase().includes(q)?'block':'none')}
function reprintExisting(id){const o=window.__ordersRows.find(x=>String(x.id)===String(id));if(o)printOrder(o)}
async function showCustomers(){let rows=[];try{const r=await api('/rest/v1/customers?select=*&order=created_at.desc&limit=1000');if(r.ok)rows=await r.json()}catch{}window.__customersRows=rows;openModal('👥 الزبائن',`<div class="search-row"><input id="customersSearch" placeholder="بحث بالاسم أو الهاتف" oninput="filterCustomers()"></div><div id="customersList">${rows.map(customerCard).join('')||'<p class="muted">لا يوجد زبائن.</p>'}</div>`)}
function customerCard(c){return `<div class="customer-card customer-record" data-search="${esc((c.name||'')+' '+(c.phone||''))}" onclick="customerDetails('${esc(c.phone||'').replace(/'/g,"\\'")}')"><strong>${esc(c.name||'بدون اسم')}</strong><br>📞 ${esc(c.phone||'')}<br>📍 ${esc(c.address||'')}<div class="muted">اضغط لعرض الطلبات والتفاصيل</div></div>`}
function filterCustomers(){const q=document.getElementById('customersSearch').value.toLowerCase();document.querySelectorAll('.customer-record').forEach(e=>e.style.display=e.dataset.search.toLowerCase().includes(q)?'block':'none')}
async function customerDetails(phone){let rows=[];try{const r=await api(`/rest/v1/orders?customer_phone=eq.${encodeURIComponent(phone)}&select=*&order=created_at.desc&limit=500`);if(r.ok)rows=await r.json()}catch{}const total=rows.reduce((s,o)=>s+Number(o.total||0),0);openModal('👤 تفاصيل الزبون',`<button class="close-btn" onclick="showCustomers()">← رجوع</button><h3>${esc((window.__customersRows.find(c=>c.phone===phone)||{}).name||'زبون')}</h3><p>📞 ${esc(phone)}</p><div class="summary-grid"><div class="summary-card">الطلبات<div class="big">${rows.length}</div></div><div class="summary-card">إجمالي الإنفاق<div class="big">$${money(total)}</div></div></div>${rows.map(orderCard).join('')||'<p>لا توجد طلبات.</p>'}`);window.__ordersRows=rows}
async function showReports(){const date=new Date().toISOString().slice(0,10);openReportForDate(date)}
async function openReportForDate(date){let rows=[];try{const from=date+'T00:00:00',to=date+'T23:59:59.999';const r=await api(`/rest/v1/orders?created_at=gte.${encodeURIComponent(from)}&created_at=lte.${encodeURIComponent(to)}&select=*&order=created_at.asc&limit=5000`);if(r.ok)rows=await r.json()}catch(e){console.warn(e)}const stats=buildReport(rows);openModal('📊 تقرير المبيعات اليومية',`<div class="search-row"><input id="reportDate" type="date" value="${date}" onchange="openReportForDate(this.value)"></div><div class="summary-grid"><div class="summary-card">عدد الطلبات<div class="big">${stats.orders}</div></div><div class="summary-card">إجمالي المبيعات<div class="big">$${money(stats.total)}</div></div><div class="summary-card">كاش<div class="big">$${money(stats.cash)}</div></div><div class="summary-card">المفروض بالصندوق<div class="big">$${money(stats.cash)}</div></div></div><h3>📦 شو انباع اليوم</h3>${stats.products.length?`<table class="report-table"><thead><tr><th>الصنف</th><th>الكمية</th><th>المجموع</th></tr></thead><tbody>${stats.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.qtyLabel}</td><td>$${money(p.total)}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">لا توجد مبيعات بهذا التاريخ.</p>'}<hr><p>🛵 دليفري: <b>$${money(stats.delivery)}</b> &nbsp; 🏪 استلام: <b>$${money(stats.pickup)}</b></p><p>💵 كاش: <b>$${money(stats.cash)}</b> &nbsp; 💳 بطاقة: <b>$${money(stats.card)}</b> &nbsp; 🏦 تحويل: <b>$${money(stats.transfer)}</b></p>`)}
function buildReport(rows){const productsMap={};let total=0,cash=0,card=0,transfer=0,delivery=0,pickup=0;for(const o of rows){total+=Number(o.total||0);if(o.order_type==='Delivery')delivery+=Number(o.total||0);else pickup+=Number(o.total||0);const meta=(Array.isArray(o.items)?o.items:[]).find(x=>x.__meta)||{};if(meta.payment_method==='card')card+=Number(o.total||0);else if(meta.payment_method==='transfer')transfer+=Number(o.total||0);else cash+=Number(o.total||0);for(const x of (Array.isArray(o.items)?o.items:[]).filter(x=>!x.__meta)){const k=x.name||x.label||'غير معروف';if(!productsMap[k])productsMap[k]={name:k,qty:0,weight:0,total:0};productsMap[k].qty+=Number(x.quantity||0);productsMap[k].weight+=Number(x.weight||0);productsMap[k].total+=Number(x.total||0)}}const products=Object.values(productsMap).sort((a,b)=>b.total-a.total).map(p=>({...p,qtyLabel:p.weight?money(p.weight)+' كغ':String(p.qty)}));return{orders:rows.length,total,cash,card,transfer,delivery,pickup,products}}
async function showMenuManager(){
 const body=`
 <div class="manager-settings"><h3>⚙️ إعدادات عامة</h3><div class="form-grid">
 <div><label>كلفة التوصيل ($)</label><input id="managerDelivery" type="number" step="0.01" min="0" value="${money(deliveryCharge)}"></div>
 <div><label>إضافة القلي والشوي لكل كغ ($)</label><input id="managerCooking" type="number" step="0.01" min="0" value="${money((Number(frySurcharge)+Number(grillSurcharge))/2)}"></div>
 <div class="full"><button class="primary" onclick="saveManagerSettings()">💾 حفظ الإعدادات</button></div></div></div>
 <hr><div class="manager-toolbar"><h3>🍽️ إدارة الأصناف والعروض</h3><div><button class="primary" onclick="openAddItemEditor()">➕ إضافة صنف</button> <button class="primary" onclick="openAddOfferEditor()">🎁 إضافة عرض</button></div></div>
 <p class="muted">من هون فيك تعدّل السعر، التفاصيل، التوفر، أو تلغي الصنف. العروض فيها تفاصيل وأصناف مكوّنة من المنيو.</p>
 <div class="manager-grid">${menu.map(managerCard).join('')}</div>`;
 openModal('⚙️ إدارة المنيو',`<div class="modal-body">${body}</div>`)}
function managerCard(i){const id=esc(i.id).replace(/'/g,"\\'");const sold=i.available===false;let editor='';if(i.type==='offer')editor=`<div class="offer-manager-details"><b>💰 السعر: $${money(i.price)}</b><p>${esc(i.details||'لا توجد تفاصيل')}</p><div class="muted">${(i.items||[]).map(x=>esc(x.name)+(x.quantity>1?' × '+x.quantity:'')).join('، ')||'لا توجد أصناف ضمن العرض'}</div></div>`;else if(i.type==='weight')editor=`<div class="price-editor"><label>السعر الأساسي / كغ ($)</label><input id="price-${esc(i.id)}" type="number" step="0.01" min="0" value="${money(i.pricing?.base)}"><button class="primary" onclick="saveItemPrice('${id}')">💾 حفظ السعر</button></div>`;else if(i.type==='sizes')editor=`<div class="price-editor sizes-editor">${Object.entries(i.sizes||{}).map(([size,p])=>`<div><label>${esc(size)} ($)</label><input id="price-${esc(i.id)}-${esc(size)}" type="number" step="0.01" min="0" value="${money(p)}"></div>`).join('')}<button class="primary" onclick="saveItemPrice('${id}')">💾 حفظ الأسعار</button></div>`;else if(i.type==='meal')editor=`<div class="price-editor"><div><label>وجبة ($)</label><input id="price-${esc(i.id)}-meal" type="number" step="0.01" min="0" value="${money(i.prices?.وجبة)}"></div><div><label>ساندويش ($)</label><input id="price-${esc(i.id)}-sandwich" type="number" step="0.01" min="0" value="${money(i.prices?.ساندويش)}"></div><button class="primary" onclick="saveItemPrice('${id}')">💾 حفظ الأسعار</button></div>`;else editor=`<div class="price-editor"><label>السعر ($)</label><input id="price-${esc(i.id)}" type="number" step="0.01" min="0" value="${money(i.price)}"><button class="primary" onclick="saveItemPrice('${id}')">💾 حفظ السعر</button></div>`;return `<div class="manager-card ${sold?'manager-sold':''}"><h4>${i.type==='offer'?'🎁 ':''}${esc(i.name)}</h4><div class="muted">${esc(i.category)}</div>${editor}<div class="manager-actions"><button class="${sold?'primary':'danger'}" onclick="toggleAvailability('${id}')">${sold?'✅ إعادة متوفر':'⛔ إخفاء/منتهي'}</button>${i.type==='offer'?`<button class="primary" onclick="openEditOffer('${id}')">✏️ تعديل العرض</button>`:`<button class="primary" onclick="openEditItem('${id}')">✏️ تعديل الصنف</button>`}<button class="danger" onclick="deleteMenuItem('${id}')">🗑️ إلغاء الصنف</button></div></div>`}
function categoryOptions(selected){return CATEGORIES.map(c=>`<option value="${esc(c)}" ${c===selected?'selected':''}>${esc(c)}</option>`).join('')}
function openAddItemEditor(){openItemEditor(null)}
function openEditItem(id){const i=menu.find(x=>x.id===id);if(i)openItemEditor(i)}
function openItemEditor(item){const i=item||{id:'',name:'',category:CATEGORIES[0],type:'fixed',price:0,available:true};openModal(item?'✏️ تعديل صنف':'➕ إضافة صنف',`<div class="form-grid"><div><label>اسم الصنف</label><input id="editName" class="modal-input" value="${esc(i.name)}"></div><div><label>التصنيف</label><select id="editCategory" class="modal-input">${categoryOptions(i.category)}</select></div><div><label>نوع الصنف</label><select id="editType" class="modal-input" onchange="refreshItemEditor()"><option value="fixed" ${i.type==='fixed'?'selected':''}>سعر عادي</option><option value="weight" ${i.type==='weight'?'selected':''}>بالكيلو</option><option value="sizes" ${i.type==='sizes'?'selected':''}>أحجام</option><option value="meal" ${i.type==='meal'?'selected':''}>وجبة/ساندويش</option></select></div><div id="itemEditorFields"></div><div class="full"><button class="primary" onclick="saveItemEditor('${esc(i.id).replace(/'/g,"\\'")}')">💾 حفظ</button></div></div>`);window.__editingItem=i;refreshItemEditor()}
function refreshItemEditor(){const i=window.__editingItem||{};const type=document.getElementById('editType').value;let html='';if(type==='weight')html=`<label>السعر الأساسي / كغ</label><input id="editBase" class="modal-input" type="number" step="0.01" value="${money(i.pricing?.base)}">`;else if(type==='sizes'){const sizes=i.sizes||{صغير:0,وسط:0,كبير:0};html=`<label>الأحجام والأسعار (مثال: صغير:5,وسط:8,كبير:11)</label><input id="editSizes" class="modal-input" value="${esc(Object.entries(sizes).map(([k,v])=>k+':'+v).join(','))}">`;}else if(type==='meal')html=`<label>وجبة ($)</label><input id="editMeal" class="modal-input" type="number" step="0.01" value="${money(i.prices?.وجبة)}"><label>ساندويش ($)</label><input id="editSandwich" class="modal-input" type="number" step="0.01" value="${money(i.prices?.ساندويش)}>`;else html=`<label>السعر ($)</label><input id="editPrice" class="modal-input" type="number" step="0.01" value="${money(i.price)}">`;document.getElementById('itemEditorFields').innerHTML=html}
async function saveItemEditor(oldId){const name=document.getElementById('editName').value.trim();if(!name)return alert('اكتب اسم الصنف.');const type=document.getElementById('editType').value;let i=oldId?menu.find(x=>x.id===oldId):null;if(!i){i={id:'item_'+Date.now(),name,category:'',type,available:true};menu.push(i)}i.name=name;i.category=document.getElementById('editCategory').value;i.type=type;if(type==='weight'){i.pricing={base:Number(document.getElementById('editBase').value)||0};delete i.stock;delete i.price;delete i.sizes;delete i.prices}else if(type==='sizes'){const obj={};for(const part of document.getElementById('editSizes').value.split(',')){const [k,v]=part.split(':');if(k&&Number.isFinite(Number(v)))obj[k.trim()]=Number(v)}if(!Object.keys(obj).length)return alert('أدخل الأحجام والأسعار.');i.sizes=obj;delete i.price;delete i.pricing;delete i.prices}else if(type==='meal'){i.prices={وجبة:Number(document.getElementById('editMeal').value)||0,ساندويش:Number(document.getElementById('editSandwich').value)||0};delete i.price;delete i.sizes;delete i.pricing}else{i.price=Number(document.getElementById('editPrice').value)||0;delete i.sizes;delete i.pricing;delete i.prices}saveMenuLocal();await syncMenuToCloud();renderCategories();renderItems();showMenuManager()}
function openAddOfferEditor(){openOfferEditor(null)}
function openEditOffer(id){const i=menu.find(x=>x.id===id);if(i)openOfferEditor(i)}
function offerItemOptions(selected){return menu.filter(x=>x.type!=='offer').map(x=>`<label class="offer-item-row"><input type="checkbox" value="${esc(x.id)}" ${(selected||[]).some(s=>s.id===x.id)?'checked':''}> ${esc(x.name)} <input class="offer-item-qty" data-id="${esc(x.id)}" type="number" min="1" step="1" value="${Number((selected||[]).find(s=>s.id===x.id)?.quantity||1)}"></label>`).join('')}
function openOfferEditor(item){const i=item||{id:'',name:'',category:'🎁 العروض',type:'offer',price:0,details:'',items:[],available:true};window.__editingOffer=i;openModal(item?'✏️ تعديل العرض':'🎁 إضافة عرض',`<div class="form-grid"><div><label>اسم العرض</label><input id="offerName" class="modal-input" value="${esc(i.name)}"></div><div><label>سعر العرض ($)</label><input id="offerPrice" class="modal-input" type="number" step="0.01" value="${money(i.price)}"></div><div class="full"><label>تفاصيل العرض</label><textarea id="offerDetails" class="modal-input" rows="3">${esc(i.details||'')}</textarea></div><div class="full"><label>الأصناف الموجودة ضمن العرض</label><div class="offer-items-picker">${offerItemOptions(i.items)}</div></div><div class="full"><button class="primary" onclick="saveOfferEditor('${esc(i.id).replace(/'/g,"\\'")}')">💾 حفظ العرض</button></div></div>`)}
async function saveOfferEditor(oldId){const name=document.getElementById('offerName').value.trim(),price=Number(document.getElementById('offerPrice').value);if(!name||!Number.isFinite(price)||price<0)return alert('تأكد من اسم العرض والسعر.');let i=oldId?menu.find(x=>x.id===oldId):null;if(!i){i={id:'offer_'+Date.now(),type:'offer',available:true,category:'🎁 العروض'};menu.push(i)}i.name=name;i.price=price;i.details=document.getElementById('offerDetails').value.trim();i.items=[...document.querySelectorAll('.offer-items-picker input[type=checkbox]:checked')].map(cb=>{const src=menu.find(x=>x.id===cb.value);const q=Number(document.querySelector(`.offer-item-qty[data-id="${cb.value}"]`)?.value||1);return{id:src.id,name:src.name,quantity:q}});saveMenuLocal();await syncMenuToCloud();renderCategories();renderItems();showMenuManager()}
async function deleteMenuItem(id){const i=menu.find(x=>x.id===id);if(!i)return;if(!confirm(`هل تريد إلغاء الصنف «${i.name}» نهائياً من إدارة المنيو؟`))return;menu=menu.filter(x=>x.id!==id);saveMenuLocal();if(navigator.onLine){try{await api(`/rest/v1/pos_menu?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'})}catch(e){console.warn(e)}}renderCategories();renderItems();showMenuManager()}
async function saveManagerSettings(){
 const d=Number(document.getElementById('managerDelivery').value),c=Number(document.getElementById('managerCooking').value);
 if(!Number.isFinite(d)||d<0||!Number.isFinite(c)||c<0)return alert('أدخل قيم صحيحة.');
 deliveryCharge=d;frySurcharge=c;grillSurcharge=c;
 localStorage.setItem(DELIVERY_CHARGE_KEY,String(d));localStorage.setItem(GLOBAL_FRY_KEY,String(c));localStorage.setItem(GLOBAL_GRILL_KEY,String(c));
 await Promise.all([saveSetting('delivery_charge',d),saveSetting('fish_fry_surcharge',c),saveSetting('fish_grill_surcharge',c)]);
 renderCart();showMenuManager();alert('✅ تم حفظ كلفة التوصيل وإضافة القلي والشوي.');
}
async function saveItemPrice(id){
 const i=menu.find(x=>x.id===id);if(!i)return;
 if(i.type==='weight'){
  const n=Number(document.getElementById('price-'+id).value);if(!Number.isFinite(n)||n<0)return alert('السعر غير صحيح.');i.pricing=i.pricing||{};i.pricing.base=n;
 }else if(i.type==='sizes'){
  const next={};for(const size of Object.keys(i.sizes||{})){const el=document.getElementById('price-'+id+'-'+size);const n=Number(el?.value);if(!Number.isFinite(n)||n<0)return alert('السعر غير صحيح.');next[size]=n}i.sizes=next;
 }else if(i.type==='meal'){
  const a=Number(document.getElementById('price-'+id+'-meal').value),b=Number(document.getElementById('price-'+id+'-sandwich').value);if(!Number.isFinite(a)||a<0||!Number.isFinite(b)||b<0)return alert('السعر غير صحيح.');i.prices={وجبة:a,ساندويش:b};
 }else{
  const n=Number(document.getElementById('price-'+id).value);if(!Number.isFinite(n)||n<0)return alert('السعر غير صحيح.');i.price=n;
 }
 saveMenuLocal();await syncMenuToCloud();renderItems();showMenuManager();
}
async function saveGlobalSurcharges(){
 const c=Number(document.getElementById('globalCooking')?.value ?? document.getElementById('globalFry')?.value);
 if(!Number.isFinite(c)||c<0)return alert('أدخل سعراً صحيحاً.');frySurcharge=c;grillSurcharge=c;localStorage.setItem(GLOBAL_FRY_KEY,String(c));localStorage.setItem(GLOBAL_GRILL_KEY,String(c));await saveSetting('fish_fry_surcharge',c);await saveSetting('fish_grill_surcharge',c);renderItems();alert('✅ تم توحيد إضافة القلي والشوي.');
}
async function saveSetting(id,value){try{const r=await api('/rest/v1/pos_settings?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id,value,updated_at:new Date().toISOString()})});if(!r.ok)console.warn(await r.text())}catch(e){console.warn(e)}}
async function toggleAvailability(id){const i=menu.find(x=>x.id===id);if(!i)return;i.available=!i.available;saveMenuLocal();await syncMenuToCloud();renderItems();showMenuManager()}
document.getElementById('phone')?.addEventListener('blur',findCustomer);
window.addEventListener('online',()=>{setStatus();syncPendingOrders();syncMenuFromCloud()});window.addEventListener('offline',setStatus);
window.addEventListener('load',async()=>{loadSettings();loadMenu();setStatus();if(sessionStorage.getItem('tabbaraLoggedIn')==='1')document.getElementById('loginScreen').style.display='none';renderCategories();renderCart();await syncMenuFromCloud()});
